---
driver_plugin: vagrant
platforms:
- name: centos-6.4-x86_64
  driver_config:
    box: opscode-centos-6.4-x86_64
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
    require_chef_omnibus: true
    customize:
      cpus: 1
      memory: 256
suites:
- name: install
  run_list:
    - recipe[cookbook_profiler]
    - recipe[datomic::default]
  attributes:
    datomic:
      java:
        '-X':
          ms: 64m
          mx: 64m
- name: upgrade
  run_list:
    - recipe[cookbook_profiler]
    - recipe[datomic::default]
    - recipe[datomic_test::upgrade]
  attributes:
    datomic:
      java:
        '-X':
          ms: 64m
          mx: 64m
