---
driver_plugin: vagrant
platforms:
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    require_chef_omnibus: 11.18.0
    customize:
      cpus: 1
      memory: 1024
suites:
- name: install
  run_list:
    - recipe[datomic::default]
  attributes:
    datomic:
      java:
        '-X':
          ms: 64m
          mx: 64m
- name: util_only_install
  run_list:
    - recipe[datomic::default]
  attributes:
    datomic:
      java:
        '-X':
          ms: 64m
          mx: 64m
      service_install: false
- name: upgrade
  run_list:
    - recipe[datomic::default]
    - recipe[datomic_test::upgrade]
  attributes:
    datomic:
      java:
        '-X':
          ms: 64m
          mx: 64m
